steps:
#- id: 'Create Container'
#  name: 'gcr.io/cloud-builders/docker'
#  args: ['build', '--tag=gcr.io/$_IMAGE_REPO/frontend:$COMMIT_SHA', 'src/frontend/']

#- id: 'Push Container to Staging registry'
#  name: 'gcr.io/cloud-builders/docker'
#  args: ["push", "gcr.io/$_IMAGE_REPO/frontend:$COMMIT_SHA"]

#- id: 'Deploy to Staging Cluster'
#  name: 'gcr.io/cloud-builders/kubectl'
#  args:
#  - 'set'
#  - 'image'
#  - 'deployment/frontend'
#  - 'server=gcr.io/$_IMAGE_REPO/frontend:$COMMIT_SHA'
#  env:
#  - 'CLOUDSDK_COMPUTE_ZONE=$_CLUSTER_ZONE'
#  - 'CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER_NAME'
#  - 'CLOUDSDK_CORE_PROJECT=$_CLUSTER_PROJECT'


- id: 'Git Clone'
  name: 'gcr.io/cloud-builders/git'
  #args: ['clone', '-b', 'staging', 'https://github.com/bkauf/microservices-demo.git']
  args: ['checkout','-B','staging']



# Prepare for github
- id: 'Copy Git SSH Auth Key into Source Folder'
  name: gcr.io/cloud-builders/gsutil
  args: ['cp', 'gs://$PROJECT_ID-github/github_rsa', '/workspace/id_rsa']


- id: 'Prepare Git Hub'
  name: 'gcr.io/cloud-builders/gcloud'
  dir: /workspace/src
  entrypoint: './githubssh.sh'
  volumes:
  - name: 'ssh-setup'
    path: /root/.ssh

#- id: 'Git Config'
#  name: 'gcr.io/cloud-builders/git'
#  args:
#  - config
#  - --global
#  - user.email
#  - brian.kaufman@gmail.com




- id: 'Get Updated Manifest'
  name: 'gcr.io/cloud-builders/kubectl'
  entrypoint: 'bash'
  dir: release
  args:
  - '-c' # pass what follows as a command to bash
  - |
    gcloud container clusters get-credentials --zone=$_CLUSTER_ZONE --project=$_CLUSTER_PROJECT $_CLUSTER_NAME
    kubectl get deployment -o yaml > deployment-manifest.yaml
#  env:
#  - 'CLOUDSDK_COMPUTE_ZONE=$_CLUSTER_ZONE'
#  - 'CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER_NAME'
#  - 'CLOUDSDK_CORE_PROJECT=$_CLUSTER_PROJECT'


#- id: 'Copy manifest '
#  name: gcr.io/cloud-builders/gsutil
#  dir: release
#  args: ['cp', 'gs://$PROJECT_ID-github/test.yaml', 'deployment-manifest.yaml']


- id: 'Git Checkout, commit'
  name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  #args:
  #- checkout
  #- -B
  #- "staging"
  - '-c' # pass what follows as a command to bash
  - |
    git config --global user.email brian.kaufman@gmail.com
    git checkout -B "staging"
    git -am commit "update manifest"

#- id: 'Git Commit'
#  name: 'gcr.io/cloud-builders/git'
#  args:
#  - commit
#  - -am
#  - "update manifest"


- id: 'GitHub Push'
  name: 'gcr.io/cloud-builders/git'
  env:
  - GIT_SSH=src/git-ssh.sh
  args:
  - push
  - git@github.com:bkauf/microservices-demo
  - staging
  volumes:
  - name: 'ssh-setup'
    path: /root/.ssh

#options:
  #machineType: 'N1_HIGHCPU_8'
