steps:
- id: 'Create Container'
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$_IMAGE_REPO/frontend:$COMMIT_SHA', 'src/frontend/']

- id: 'Push Container to Staging registry'
  name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$_IMAGE_REPO/frontend:$COMMIT_SHA"]

- id: 'Deploy to Staging Cluster'
  name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'image'
  - 'deployment/frontend'
  - 'server=gcr.io/$_IMAGE_REPO/frontend:$COMMIT_SHA'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=$_CLUSTER_ZONE'
  - 'CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER_NAME'
  - 'CLOUDSDK_CORE_PROJECT=$_CLUSTER_PROJECT'

- id: 'Update manifest'
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
     sed "s/(image:.*(frontend:.*))/image: gcr.io/$_IMAGE_REPO/frontend:$COMMIT_SHA/g" release/kubernetes-manifest.yaml

- id: 'Push Manifest'
- name: gcr.io/cloud-builders/git
  args: ['push', 'https://github.com/bkauf/microservices-demo', 'master']
#options:
  #machineType: 'N1_HIGHCPU_8'
