steps:

- id: 'Create Container'
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/cicd-march-25th/frontend:$TAG_NAME', 'src/frontend/']

- id: 'Push Container to Staging registry'
  name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/cicd-march-25th/frontend:$TAG_NAME"]

- id: 'Deploy to Staging Cluster'
  name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'image'
  - 'deployment/frontend'
  - 'server=gcr.io/cicd-march-25th/frontend:$TAG_NAME'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=spinnaker-tutorial'
  - 'CLOUDSDK_CORE_PROJECT=cicd-march-25th'
options:
 machineType: 'N1_HIGHCPU_8'
